name: Webseite Updaten

on:
  push:
    branches-ignore:
      - dev
      - build
    paths:
      - '**'
  pull_request:
    branches-ignore:
      - dev
      - build
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: upload to webpage
    steps:
      - name: CALL WEB API
        if: github.ref == 'refs/heads/main'
        run:
          curl https://lff.one/server/git/gitPull.api
